version: "3.4"

services:
  ffmpeg-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ffmpeg-api
    restart: always
    ports:
      - 9001:9001

  whisper-asr:
    container_name: whisper-asr
    image: "onerahmet/openai-whisper-asr-webservice:latest"
    restart: always
    ports:
      - "9000:9000"
    environment:
      ASR_MODEL: base.en
      ASR_ENGINE: faster_whisper
    volumes:
      - ./.cache/whisper:/root/.cache/whisper
      - ./.cache/faster_whisper:/root/.cache/faster_whisper
