version: "3.4"

services:
  ffmpeg-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ffmpeg-api
    networks:
      - shared
    restart: always
    ports:
      - 1337:1337

  whisper-asr-webservice-gpu:
    container_name: whisper-asr-gpu
    image: "onerahmet/openai-whisper-asr-webservice:latest-gpu"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
    networks:
      - shared
    expose:
      - 9000
    environment:
      ASR_MODEL: base.en
      ASR_ENGINE: faster_whisper
    volumes:
      - ./.cache/whisper:/root/.cache/whisper
      - ./.cache/faster_whisper:/root/.cache/faster_whisper

networks:
  shared:
    driver: bridge
